In [102]:
import numpy as np

In [103]:
sales = [0,5,155,0,518,0,1343,5454,655,343]
print(sales)
print(type(sales))

[0, 5, 155, 0, 518, 0, 1343, 5454, 655, 343]
<class 'list'>


In [104]:
sales_array = np.array(sales)
print(sales_array)
print(type(sales_array))

[   0    5  155    0  518    0 1343 5454  655  343]
<class 'numpy.ndarray'>


In [105]:
print(sales_array.shape)
print(sales_array.size)
print(sales_array.ndim)
print(sales_array.dtype)

(10,)
10
1
int64


In [106]:
sales_a = [[12,121,34,53,34], [33,32,42,1,423]]
sales_array = np.array(sales_a)
print(sales_array)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.ndim)
print(sales_array.dtype)

[[ 12 121  34  53  34]
 [ 33  32  42   1 423]]
(2, 5)
10
2
int64


In [107]:
array = np.array(range(5))
print(array)

[0 1 2 3 4]


In [108]:
array_2d = np.array([range(5), range(5)])
print(array_2d)

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [109]:
array_2d +1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [110]:
array_2d*2

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [111]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [112]:
array_2d.T.shape

(5, 2)

#### Assignment 

In [114]:
my_list = [x * 10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [115]:
my_array = np.array(my_list)
print(my_array)
print(my_array.size)
print(my_array.shape)
print(my_array.ndim)
print(my_array.dtype)

[ 10  20  30  40  50  60  70  80  90 100]
10
(10,)
1
int64
