In [146]:
import numpy as np

In [147]:
sales = [0,5,155,0,518,0,1343,5454,655,343]
print(sales)
print(type(sales))

[0, 5, 155, 0, 518, 0, 1343, 5454, 655, 343]
<class 'list'>


In [148]:
sales_array = np.array(sales)
print(sales_array)
print(type(sales_array))

[   0    5  155    0  518    0 1343 5454  655  343]
<class 'numpy.ndarray'>


In [149]:
print(sales_array.shape)
print(sales_array.size)
print(sales_array.ndim)
print(sales_array.dtype)

(10,)
10
1
int64


In [150]:
sales_a = [[12,121,34,53,34], [33,32,42,1,423]]
sales_array = np.array(sales_a)
print(sales_array)
print(sales_array.shape)
print(sales_array.size)
print(sales_array.ndim)
print(sales_array.dtype)

[[ 12 121  34  53  34]
 [ 33  32  42   1 423]]
(2, 5)
10
2
int64


In [151]:
array = np.array(range(5))
print(array)

[0 1 2 3 4]


In [152]:
array_2d = np.array([range(5), range(5)])
print(array_2d)

[[0 1 2 3 4]
 [0 1 2 3 4]]


In [153]:
array_2d +1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [154]:
array_2d*2

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [155]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [156]:
array_2d.T.shape

(5, 2)

#### Assignment 

In [157]:
my_list = [x * 10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [158]:
my_array = np.array(my_list)
print(my_array)
print(my_array.size)
print(my_array.shape)
print(my_array.ndim)
print(my_array.dtype)

[ 10  20  30  40  50  60  70  80  90 100]
10
(10,)
1
int64


In [159]:
my_array.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [160]:
my_array.reshape(1,10)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [161]:
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [162]:
my_array.reshape(-1,1)

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [163]:
arr = np.array([2,3,4,5]).reshape(2,2)
arr

array([[2, 3],
       [4, 5]])

In [164]:
arr.T

array([[2, 4],
       [3, 5]])

#### Inbuilt numerical data creation numpy

In [165]:
np.ones(4,int)

array([1, 1, 1, 1])

In [166]:
np.ones((4,4), float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [167]:
np.zeros(4,int)

array([0, 0, 0, 0])

In [168]:
np.zeros(4,int).reshape(2,2)

array([[0, 0],
       [0, 0]])

In [169]:
np.zeros((4,4), float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
np.arange(2,10,1).reshape(2,4)

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [171]:
np.linspace(0,100,5) # it will provide 5 elements at equal distance between 0 and 100
#These are very useful for chart axis and other labels

array([  0.,  25.,  50.,  75., 100.])

In [172]:
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [177]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [178]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [183]:
np.linspace(2,12,50)

array([ 2.        ,  2.20408163,  2.40816327,  2.6122449 ,  2.81632653,
        3.02040816,  3.2244898 ,  3.42857143,  3.63265306,  3.83673469,
        4.04081633,  4.24489796,  4.44897959,  4.65306122,  4.85714286,
        5.06122449,  5.26530612,  5.46938776,  5.67346939,  5.87755102,
        6.08163265,  6.28571429,  6.48979592,  6.69387755,  6.89795918,
        7.10204082,  7.30612245,  7.51020408,  7.71428571,  7.91836735,
        8.12244898,  8.32653061,  8.53061224,  8.73469388,  8.93877551,
        9.14285714,  9.34693878,  9.55102041,  9.75510204,  9.95918367,
       10.16326531, 10.36734694, 10.57142857, 10.7755102 , 10.97959184,
       11.18367347, 11.3877551 , 11.59183673, 11.79591837, 12.        ])

In [188]:
np.linspace(0,10,100).reshape(-1,1)

array([[ 0.        ],
       [ 0.1010101 ],
       [ 0.2020202 ],
       [ 0.3030303 ],
       [ 0.4040404 ],
       [ 0.50505051],
       [ 0.60606061],
       [ 0.70707071],
       [ 0.80808081],
       [ 0.90909091],
       [ 1.01010101],
       [ 1.11111111],
       [ 1.21212121],
       [ 1.31313131],
       [ 1.41414141],
       [ 1.51515152],
       [ 1.61616162],
       [ 1.71717172],
       [ 1.81818182],
       [ 1.91919192],
       [ 2.02020202],
       [ 2.12121212],
       [ 2.22222222],
       [ 2.32323232],
       [ 2.42424242],
       [ 2.52525253],
       [ 2.62626263],
       [ 2.72727273],
       [ 2.82828283],
       [ 2.92929293],
       [ 3.03030303],
       [ 3.13131313],
       [ 3.23232323],
       [ 3.33333333],
       [ 3.43434343],
       [ 3.53535354],
       [ 3.63636364],
       [ 3.73737374],
       [ 3.83838384],
       [ 3.93939394],
       [ 4.04040404],
       [ 4.14141414],
       [ 4.24242424],
       [ 4.34343434],
       [ 4.44444444],
       [ 4